# Generated by Django 5.2 on 2025-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_message_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointements",
            name="notification",
            field=models.CharField(blank=True, null=True),
        ),
    ]
