# Generated by Django 5.2 on 2025-05-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_appointements_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "prediction",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
            ],
        ),
    ]
