# Generated by Django 5.2 on 2025-05-05 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_imageprediction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageprediction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
