# Generated by Django 5.2 on 2025-05-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_imageprediction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageprediction",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
