# Generated by Django 5.2 on 2025-05-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_imageprediction_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accountCode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="accountNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
